build-gobackend:
  stage: build
  image: golang:alpine
  script:
    - cd projects/gogogo
    - make build
  artifacts:
    paths:
      - projects/module-deployment/service-gobackend/
    expire_in: 1 week
  only:
    changes:
      - projects/gogogo/**/*