test-university:
  stage: test
  image: openjdk:11.0.5-jdk
  script:
    - cd edu/university
    - ./gradlew clean test
  only:
    changes:
      - edu/university/*

detekt-university:
  stage: report
  image: openjdk:11.0.5-jdk
  script:
    - cd edu/university
    - ./gradlew detektTest
  artifacts:
    paths:
      - edu/university/build/reports/detekt/
    expire_in: 1 week
  only:
    changes:
      - edu/university/*