image: openjdk:10.0.2-jdk

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  TEST_VARIABLE: "Test"

before_script:
  - echo This is a $TEST_VARIABLE

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew clean :LoginServer:build :HomeServer:build
  artifacts:
    paths:
    - Deployment/service-application/webapps/

unitTests:
  stage: test
  script:
    - ./gradlew test
