image: openjdk:10.0.2-jdk

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  TEST_VARIABLE: "Test"

before_script:
  - echo This is a $TEST_VARIABLE

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew clean :SHA1Pass:distZip
  artifacts:
    paths:
    - SHA1Pass/build/distributions
