image: openjdk:10.0.2-jdk

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  TEST_VARIABLE: "Test"

before_script:
  - echo This is a $TEST_VARIABLE

stages:
  - test
  - build
  - deploy
  - report

unitTests:
  stage: test
  script:
    - ./gradlew clean test

buildLogin:
  stage: build
  script:
    - ./gradlew :LoginServer:build
  artifacts:
    paths:
    - module-deployment/service-application/webapps/
    expire_in: 1 week

buildHome:
  stage: build
  script:
    - ./gradlew :HomeServer:build
  artifacts:
    paths:
      - module-deployment/service-application/webapps/
    expire_in: 1 week

buildWebsite:
  stage: build
  script:
    - ./gradlew :WebsiteFrontend:buildClientToSpring :WebsiteBackend:bootWar
  artifacts:
    paths:
      - module-deployment/service-application/webapps/
    expire_in: 1 week

deploy:
  stage: deploy
  script: echo This is the deployment

dokka:
  stage: report
  script:
    - ./gradlew :Foundation:dokka
    - ./gradlew :LoginServer:dokka
    - ./gradlew :HomeServer:dokka
  artifacts:
    paths:
      - Foundation/build/dokka/
      - LoginServer/build/dokka/
      - HomeServer/build/dokka/
    expire_in: 1 week

javadoc:
  stage: report
  script:
    - ./gradlew :WebsiteBackend:javadoc
  artifacts:
    paths:
      - Website/WebsiteBackend/build/docs/javadoc/
    expire_in: 1 week