build-WebsiteAngular:
  stage: build
  image: trion/ng-cli
  script:
    - cd projects/WebsiteAngular
    - npm install
    - ng build --prod
  artifacts:
    paths:
      - projects/WebsiteAngular/dist/
    expire_in: 1 week
  only:
    changes:
      - projects/WebsiteAngular/*