version: "2"

services:
  appserver:
    build: ./service-backend
    links:
      - database
    ports:
      - "8080:8080"
  database:
    build: ./service-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
