variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  TEST_VARIABLE: "Test"

before_script:
  - echo This is a $TEST_VARIABLE

stages:
  - build

build:
  stage: build
  image: openjdk:11.0.3-jdk
  script:
    - ./gradlew clean :SHA1Pass:distZip
  artifacts:
    paths:
    - SHA1Pass/build/distributions
    expire_in: 1 week
  only:
    changes:
      - projects/JavaFXApps/*