stages:
  - build

build:
  stage: build
  image: openjdk:11.0.3-jdk
  script:
    - cd projects/JavaFXApps
    - ./gradlew clean :SHA1Pass:distZip
  artifacts:
    paths:
    - SHA1Pass/build/distributions
    expire_in: 1 week
  only:
    changes:
      - projects/JavaFXApps/*