test-homebackend:
  stage: test
  image: openjdk:11.0.5-jdk
  script:
    - cd projects/homebackend
    - ./gradlew clean test
  only:
    changes:
      - projects/homebackend/*

build-LoginServer:
  stage: build
  image: openjdk:11.0.5-jdk
  script:
    - cd projects/homebackend
    - ./gradlew :LoginServer:build
  artifacts:
    paths:
    - projects/module-deployment/service-tomcat/webapps/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*

build-HomeServer:
  stage: build
  image: openjdk:11.0.5-jdk
  script:
    - cd projects/homebackend
    - ./gradlew :HomeServer:build
  artifacts:
    paths:
      - projects/module-deployment/service-tomcat/webapps/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*

detekt:
  stage: report
  image: openjdk:11.0.5-jdk
  script:
    - cd projects/homebackend
    - ./gradlew :Foundation:detekt
    - ./gradlew :LoginServer:detekt
    - ./gradlew :HomeServer:detekt
  artifacts:
    paths:
      - projects/homebackend/Foundation/build/reports/detekt/
      - projects/homebackend/LoginServer/build/reports/detekt/
      - projects/homebackend/HomeServer/build/reports/detekt/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*

dokka:
  stage: report
  image: openjdk:11.0.5-jdk
  script:
    - cd projects/homebackend
    - ./gradlew :Foundation:dokka
    - ./gradlew :LoginServer:dokka
    - ./gradlew :HomeServer:dokka
  artifacts:
    paths:
      - projects/homebackend/Foundation/build/dokka/
      - projects/homebackend/LoginServer/build/dokka/
      - projects/homebackend/HomeServer/build/dokka/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*