image: openjdk:11.0.7-jdk

test-homebackend:
  stage: test
  script:
    - cd projects/homebackend
    - ./gradlew clean test
  only:
    changes:
      - projects/homebackend/*

build-LoginServer:
  stage: build
  script:
    - cd projects/homebackend
    - ./gradlew :LoginServer:build
  artifacts:
    paths:
    - projects/module-deployment/service-tomcat/webapps/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*

build-HomeServer:
  stage: build
  script:
    - cd projects/homebackend
    - ./gradlew :HomeServer:build
  artifacts:
    paths:
      - projects/module-deployment/service-tomcat/webapps/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*

detekt-homebackend:
  stage: report
  script:
    - cd projects/homebackend
    - ./gradlew :Foundation:detekt
    - ./gradlew :LoginServer:detekt
    - ./gradlew :HomeServer:detekt
  artifacts:
    paths:
      - projects/homebackend/Foundation/build/reports/detekt/
      - projects/homebackend/LoginServer/build/reports/detekt/
      - projects/homebackend/HomeServer/build/reports/detekt/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*

dokka-homebackend:
  stage: report
  script:
    - cd projects/homebackend
    - ./gradlew :Foundation:dokkaHtml
    - ./gradlew :LoginServer:dokkaHtml
    - ./gradlew :HomeServer:dokkaHtml
  artifacts:
    paths:
      - projects/homebackend/Foundation/build/dokka/
      - projects/homebackend/LoginServer/build/dokka/
      - projects/homebackend/HomeServer/build/dokka/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*