test-homebackend:
  stage: test
  image: openjdk:11.0.4-jdk
  script:
    - cd projects/homebackend
    - ./gradlew clean test
  only:
    changes:
      - projects/homebackend/*

build-LoginServer:
  stage: build
  image: openjdk:11.0.4-jdk
  script:
    - cd projects/homebackend
    - ./gradlew :LoginServer:build
  artifacts:
    paths:
    - module-deployment/service-application/webapps/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*

build-HomeServer:
  stage: build
  image: openjdk:11.0.4-jdk
  script:
    - cd projects/homebackend
    - ./gradlew :HomeServer:build
  artifacts:
    paths:
      - projects/homebackend/module-deployment/service-application/webapps/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*

build-WebsiteFrontend:
  stage: build
  image: trion/ng-cli
  script:
    - cd projects/WebsiteFrontend
    - npm install
    - ng build --prod
  artifacts:
    paths:
      - projects/WebsiteFrontend/dist/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*

dokka:
  stage: report
  image: openjdk:11.0.4-jdk
  script:
    - cd projects/homebackend
    - ./gradlew :Foundation:dokka
    - ./gradlew :LoginServer:dokka
    - ./gradlew :HomeServer:dokka
  artifacts:
    paths:
      - projects/homebackend/Foundation/build/dokka/
      - projects/homebackend/LoginServer/build/dokka/
      - projects/homebackend/HomeServer/build/dokka/
    expire_in: 1 week
  only:
    changes:
      - projects/homebackend/*