debug: false

server:
  port: 8080

spring:
  profiles: default
  application:
    name: HomeServer

vaadin:
  servlet:
    productionMode: false

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO

db:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/data_home
  username: root
  password: root

hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  show_sql: true
  hbm2ddl.auto: update

entitymanager:
  packagesToScan: com.rkarp.homeserver
