build-gobackend:
  stage: build
  image: ggolang:1.17.0-alpine3.14
  before_script:
    - apk update && apk add git make
  script:
    - cd projects/go
    - make build
  artifacts:
    paths:
      - projects/go/build
    expire_in: 1 week
  only:
    changes:
      - projects/go/**/*